"""
Type definitions for the trading engine.
"""
from dataclasses import dataclass
from datetime import datetime
from typing import Optional, List, Dict, Any


@dataclass
class Signal:
    """Trading signal generated by the signal generator."""
    direction: str  # 'buy' or 'sell'
    entry_type: str  # 'structure_break', 'pullback_continuation', 'liquidity_sweep'
    confidence: float  # 0-100
    timestamp: datetime
    reason: str  # Human-readable explanation
    price: float  # Entry price level
    alignment_result: Optional[Dict[str, Any]] = None  # Trend alignment metadata


@dataclass
class Trade:
    """Executed trade record."""
    ticket: int
    symbol: str
    direction: str  # 'buy' or 'sell'
    entry_price: float
    lot_size: float
    stop_loss: float
    take_profit: float
    entry_time: datetime
    exit_time: Optional[datetime]
    pnl: float
    exit_reason: Optional[str]  # 'take_profit', 'stop_loss', 'time_limit', 'momentum_reversal', etc.
    hold_time_seconds: Optional[float] = None


@dataclass
class Position:
    """Open position from MT5."""
    ticket: int
    symbol: str
    type: int  # MT5 order type: 0=buy, 1=sell
    volume: float  # Lot size
    price_open: float
    sl: float  # Stop loss
    tp: float  # Take profit
    profit: float  # Current profit in account currency
    time: datetime  # Open time
    partial_closed: bool = False
    partial_closed_percent: float = 0.0


@dataclass
class MarketData:
    """Market data container."""
    m1_candles: List[Dict[str, Any]]  # List of OHLC candles
    m5_candles: List[Dict[str, Any]]
    current_price: float  # Current bid/ask midpoint
    bid: float
    ask: float
    spread: float  # Spread in points
    indicators: Dict[str, Any]  # EMA, RSI, ATR values


@dataclass
class Candle:
    """OHLC candle data."""
    time: datetime
    open: float
    high: float
    low: float
    close: float
    volume: int = 0


@dataclass
class AccountInfo:
    """MT5 account information."""
    equity: float
    balance: float
    margin: float
    free_margin: float
    margin_level: float
    currency: str = "USD"


@dataclass
class CircuitBreakerState:
    """Circuit breaker current state."""
    halted: bool
    reason: Optional[str]
    halt_start_time: Optional[datetime]
    duration_minutes: int
    adjusted_risk_percent: float
    adjusted_confidence_threshold: float
    loss_count: int


